In [2]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_excel('FF_2024.xlsx', sheet_name='positional_raw')

In [12]:
df.head()

               Team    Owner  Week Group           Player  Points  Year
0  Gee Whiz Darnell  Brenton     1    QB  Trevor Lawrence   11.28   2024
1  Gee Whiz Darnell  Brenton     1    WR      Jayden Reed   31.10   2024
2  Gee Whiz Darnell  Brenton     1    WR      Tyreek Hill   22.50   2024
3  Gee Whiz Darnell  Brenton     1    WR      Zay Flowers    8.10   2024
4  Gee Whiz Darnell  Brenton     1    TE     Trey McBride    5.50   2024

#### Get rank by position and week

In [13]:
df['Type'] = df['Group'].apply(lambda x: 'RB' if 'RB' in x else ('WR' if 'WR' in x else ('TE' if 'TE' in x else x))) 
df['rank_per_week'] = df.groupby(['Year ', 'Type', 'Week', 'Team'])['Points'].rank(ascending=False, method='min')

In [14]:
df.head(22)

,Team,Owner,Week,Group,Player,Points,Year,Type,rank_per_week
0,Gee Whiz Darnell,Brenton,1,QB,Trevor Lawrence,11.28,2024,QB,1.0
1,Gee Whiz Darnell,Brenton,1,WR,Jayden Reed,31.10,2024,WR,1.0
2,Gee Whiz Darnell,Brenton,1,WR,Tyreek Hill,22.50,2024,WR,2.0
3,Gee Whiz Darnell,Brenton,1,WR,Zay Flowers,8.10,2024,WR,3.0
4,Gee Whiz Darnell,Brenton,1,TE,Trey McBride,5.50,2024,TE,1.0
5,Gee Whiz Darnell,Brenton,1,DEF,Cincinnati,3.00,2024,DEF,1.0
6,Gee Whiz Darnell,Brenton,1,K,Tyler Bass,10.00,2024,K,1.0
7,Gee Whiz Darnell,Brenton,1,RB,Jerome Ford,15.90,2024,RB,1.0
8,Gee Whiz Darnell,Brenton,1,RB,Javonte Williams,2.80,2024,RB,2.0
9,Gee Whiz Darnell,Brenton,1,RB-Flex,Christian McCaffrey,0.00,2024,RB,3.0
10,8Chane,Todd,1,QB,Dak Prescott,11.46,2024,QB,1.0
11,8Chane,Todd,1,WR,AJ Brown,20.40,2024,WR,1.0
12,8Chane,Todd,1,WR,Deebo Samuel,16.20,2024,WR,2.0
13,8Chane,Todd,1,WR,Rashee Rice,13.80,2024,WR,3.0
14,8Chane,Todd,1,RB,De'Von Achane,19.50,2024,RB,1.0
15,8Chane,Todd,1,RB,James Conner,17.80,2024,RB,2.0
16,8Chane,Todd,1,TE,Pat Freiermuth,4.70,2024,TE,1.0
17,8Chane,Todd,1,DEF,Seattle,10.00,2024,DEF,1.0
18,8Chane,Todd,1,K,Younghoe Koo,4.00,2024,K,1.0
19,8Chane,Todd,1,WR-Flex,Calvin Ridley,6.50,2024,WR,4.0
20,Pierogi Night,Mike,1,QB,Patrick Mahomes,14.64,2024,QB,1.0
21,Pierogi Night,Mike,1,WR,Davante Adams,8.40,2024,WR,3.0

### By Position

In [15]:
dfr = df[(df['Week']<=15) & (df['Year ']==2024)]
qb = dfr[dfr['Group']=='QB']
rb = dfr[dfr['Group']=='RB']
wr = dfr[dfr['Group']=='WR']
te = dfr[dfr['Group']=='TE']
dst = dfr[dfr['Group']=='DEF']
k = dfr[dfr['Group']=='K']


wr1 = dfr[(dfr['Type']=='WR')&(dfr['rank_per_week']==1)]
wr2 = dfr[(dfr['Type']=='WR')&(dfr['rank_per_week']==2)]
wr3 = dfr[(dfr['Type']=='WR')&(dfr['rank_per_week']==3)]
wr4 = dfr[(dfr['Type']=='WR')&(dfr['rank_per_week']==4)]

rb1 = dfr[(dfr['Type']=='RB')&(dfr['rank_per_week']==1)]
rb2 = dfr[(dfr['Type']=='RB')&(dfr['rank_per_week']==2)]
rb3 = dfr[(dfr['Type']=='RB')&(dfr['rank_per_week']==3)]

qbd = pd.DataFrame(qb.groupby(['Team','Owner']).mean()['Points'])
dstd = pd.DataFrame(dst.groupby(['Team','Owner']).mean()['Points'])
kd = pd.DataFrame(k.groupby(['Team','Owner']).mean()['Points'])

In [19]:
rbd = pd.DataFrame(rb.groupby(['Team','Owner','rank_per_week']).mean()['Points'])
wrd = pd.DataFrame(wr.groupby(['Team','Owner','rank_per_week']).mean()['Points'])

In [22]:
overall = pd.DataFrame(dfr.groupby(['Team','Owner','Group']).mean()['Points'])
overall

                                                           Points
Team                           Owner           Group
8Chane                         Todd            DEF       5.466667
                                               K        10.333333
                                               QB       16.026667
                                               RB       13.890000
                                               RB-Flex   3.000000
                                               TE        7.566667
                                               WR       13.244444
                                               WR-Flex   3.457143
Bijan the second date          Eli             DEF       4.733333
                                               K         9.333333
                                               QB       21.265333
                                               RB       11.600000
                                               RB-Flex   4.900000
                                               TE        9.313333
                                               TE-Flex   8.733333
                                               WR       11.301778
                                               WR-Flex   4.060000
Brady come back u can blame it Will            DEF       7.666667
                                               K         7.000000
                                               QB       13.673333
                                               RB       10.223333
                                               RB-Flex   4.500000
                                               TE        8.793333
                                               TE-Flex   4.900000
                                               WR       14.061778
                                               WR-Flex   6.992308
GOBias Industries              Schulwolf       DEF       9.800000
                                               K        10.600000
                                               QB       18.112000
                                               RB       16.363333
...                                                           ...
Pay Dirt & Pylons IV           Cam             TE       11.746667
                                               TE-Flex   4.700000
                                               WR       13.931111
                                               WR-Flex   6.825000
Pierogi Night                  Mike            DEF       8.000000
                                               K         8.933333
                                               QB       17.033333
                                               RB       15.873333
                                               RB-Flex   8.587500
                                               TE        7.420000
                                               TE-Flex   4.950000
                                               WR       11.900000
                                               WR-Flex   2.380000
Sackwash Lyfe                  Tommy           DEF       8.666667
                                               K         8.533333
                                               QB       23.710667
                                               RB       18.483333
                                               RB-Flex   8.860000
                                               TE        7.693333
                                               TE-Flex   6.000000
                                               WR       10.624444
                                               WR-Flex   4.150000
Schmaap                        Burnett/Jasjaap DEF       8.733333
                                               K         9.200000
                                               QB       17.473333
                                               RB       15.964000
                                               RB-Flex   6.770000
                                               TE       11.300000
                                               WR       12.333333
                                               WR-Flex   4.020000

[103 rows x 1 columns]

In [27]:
pivot_df = overall.pivot_table(index='Team', columns='Group', values='Points')
pivot_df = pivot_df.round(2)

In [28]:
pivot_df

Group,DEF,K,QB,RB,RB-Flex,TE,TE-Flex,WR,WR-Flex
Team,,,,,,,,,
8Chane,5.47,10.33,16.03,13.89,3.00,7.57,NaN,13.24,3.46
Bijan the second date,4.73,9.33,21.27,11.60,4.90,9.31,8.73,11.30,4.06
Brady come back u can blame it,7.67,7.00,13.67,10.22,4.50,8.79,4.90,14.06,6.99
GOBias Industries,9.80,10.60,18.11,16.36,5.75,6.62,NaN,13.67,3.98
Gee Whiz Darnell,7.00,7.20,16.91,8.88,1.93,12.33,13.10,11.49,4.07
Grip Hamilton Memorial 5k,10.00,8.47,14.35,14.95,7.10,7.05,NaN,10.78,2.72
Herbin Legends,6.80,9.07,11.17,14.01,7.67,7.09,6.00,10.31,3.26
Mr. Fans Noodle Haus,7.87,10.73,24.30,14.48,8.73,7.05,NaN,9.26,0.50
Pay Dirt & Pylons IV,6.00,8.07,21.08,14.09,6.42,11.75,4.70,13.93,6.82
Pierogi Night,8.00,8.93,17.03,15.87,8.59,7.42,4.95,11.90,2.38
Sackwash Lyfe,8.67,8.53,23.71,18.48,8.86,7.69,6.00,10.62,4.15
Schmaap,8.73,9.20,17.47,15.96,6.77,11.30,NaN,12.33,4.02

## Kitchell