In [3]:
import pandas as pd
import numpy as np
import random
pd.set_option('display.max_columns', None)

In [48]:
FF_2023 = pd.read_excel('FF_2023.xlsx')
FF_2023_summary = FF_2023[['Team_Name', 'Mean']].drop(12, 0)

In [49]:
FF_2023_summary

                    Team_Name        Mean
0   PurpleVector Reunion Tour  119.958667
1               Sackwash Lyfe  122.234667
2    Brady really was washed…  121.860000
3            Gee Whiz Darnell  121.608000
4        Mr. Fans Noodle Haus  120.169333
5              Herbin Legends  104.194667
6       Pay Dirt & Pylons III  102.645333
7               2 Movin' 2 Up  112.144000
8           GOBias Industries  106.381333
9                     Schmaap  113.336000
10     Alternative Hypothesis  105.884000
11              Pierogi Night  106.270667

In [50]:
std = 22
games = 15

def simulate_one_season_scores(df):
    Kevin_scores = np.random.normal(df.loc[0, 'Mean'], std, games)
    Tommy_scores = np.random.normal(df.loc[1, 'Mean'], std, games)
    Jay_scores = np.random.normal(df.loc[2, 'Mean'], std, games)
    Will_scores = np.random.normal(df.loc[3, 'Mean'], std, games)
    Wolf_scores = np.random.normal(df.loc[4, 'Mean'], std, games)
    Brenton_scores = np.random.normal(df.loc[5, 'Mean'], std, games)
    Todd_scores = np.random.normal(df.loc[6, 'Mean'], std, games)
    Eli_scores = np.random.normal(df.loc[7, 'Mean'], std, games)
    Brand_scores = np.random.normal(df.loc[8, 'Mean'], std, games)
    Cam_scores = np.random.normal(df.loc[9, 'Mean'], std, games)
    Burnett_scores = np.random.normal(df.loc[10, 'Mean'], std, games)
    Mike_scores = np.random.normal(df.loc[11, 'Mean'], std, games)
    
    SCORES = np.array([Kevin_scores, Tommy_scores, Jay_scores, Will_scores, 
                       Wolf_scores, Brenton_scores, Todd_scores, Eli_scores, 
                       Brand_scores, Cam_scores, Burnett_scores, Mike_scores])
    return(SCORES)

In [51]:
simulate_one_season_scores(FF_2023_summary)

array([[ 143.08788837,  135.34046739,  126.02009369,  139.4630253 ,
         106.79162664,  139.72768604,  131.19142825,  141.94939796,
         110.53863506,  136.18973422,  124.95128451,  128.24538872,
         131.33751209,  136.79965677,  111.10800203],
       [ 165.42687231,   86.24087975,  135.81648068,  106.02032189,
         136.71773233,  100.58420343,  142.86908561,  108.33488207,
         105.99411451,  159.9446075 ,  140.02224664,  146.842377  ,
          94.96521195,   76.51665369,  156.53859568],
       [ 106.34094659,  109.36210637,   85.45833053,  104.19961029,
         126.3378494 ,  133.59685674,  111.70265006,  131.54305234,
         148.3466318 ,  122.22822977,   86.43513041,  120.14890705,
         102.7442316 ,   82.71836572,  114.90599144],
       [ 119.73855067,  101.27976156,  104.65341663,  126.3926886 ,
         135.98406955,  120.67460184,  105.27095084,   58.25397947,
         127.5634267 ,  109.21771754,  124.99767145,  133.74492359,
          96.36472048,   80.03785307,  115.59188561],
       [ 121.00428404,  125.67303435,  102.52885738,  104.30059786,
         148.70214717,  149.33102518,  150.28576526,  141.69553209,
         123.5878027 ,  119.64454938,  123.22608291,   99.15123737,
         125.56871969,  130.96331651,  134.98027126],
       [  69.26893859,  120.7595375 ,  105.08088965,  121.60011336,
         125.25059204,   95.88348414,  100.32347082,  110.64140793,
          86.91138563,   88.46385463,   89.77782378,   69.42859213,
         107.7562448 ,   73.44783863,   98.15733549],
       [ 102.4520728 ,  105.2001999 ,   86.63190176,   82.0221992 ,
          62.93804709,   67.81441032,   85.8326791 ,  128.58449683,
          79.30674781,  129.39333908,   93.12870962,   78.11196961,
         103.81279538,  122.40790495,  116.04442183],
       [ 164.66932702,   85.78225446,  112.0539928 ,   99.82687601,
         153.40475559,  132.04804045,  110.24298545,  112.73456359,
          89.60804965,  134.33232919,  119.85391315,   86.83606547,
         142.39322941,  140.52567755,   87.17677771],
       [ 105.26429766,  130.53496509,  106.63180061,   89.00449374,
         146.64503764,   70.26712113,  120.7177476 ,  111.80179575,
         100.42360282,  129.08385661,  115.28073804,  110.49709501,
         123.99599966,  113.10117628,  102.27752021],
       [ 119.19643596,   89.59527833,   91.57067307,  134.50663863,
          98.94101433,  133.0949172 ,  101.11295546,   95.48302545,
          93.12977285,  133.07394004,   92.90423144,   82.8213595 ,
         141.75364578,  102.59197997,  133.7943741 ],
       [ 113.69584783,  121.29441802,  101.29817692,   82.18086807,
          73.90474154,   84.67392376,  144.16963371,  112.79563267,
          86.90793534,   82.20625433,   98.4544499 ,  114.77157552,
         121.93246912,   98.02548427,  110.2717834 ],
       [ 120.52114938,   99.32369754,   82.79763104,  103.7884214 ,
         127.97220201,   59.04008673,  134.90598072,  106.10409198,
         114.04505533,  130.58073781,  122.93227041,  115.12881726,
          91.23259513,   75.71832157,  104.11627755]])

In [52]:
def week1(scores_array, wins_array):
    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 'Wolf':4, 'Brenton':5, 'Todd':6,
            'Eli':7, 'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference
    
    #Brenton vs. Jay
    if scores_array[5][0] > scores_array[2][0]:
        wins_array[5] =+ 1
    else:
        wins_array[2] =+ 1
    
    #Mike vs. Burnett   
    if scores_array[11][0] > scores_array[10][0]:
        wins_array[11] =+ 1
    else:
        wins_array[10] =+ 1
    
    #Will vs. Brand
    if scores_array[3][0] > scores_array[8][0]:
        wins_array[3] =+ 1
    else:
        wins_array[8] =+ 1
        
    #Wolf vs. Eli
    if scores_array[4][0] > scores_array[7][0]:
        wins_array[4] =+ 1
    else:
        wins_array[7] =+ 1
        
    #Todd vs. Cam
    if scores_array[6][0] > scores_array[9][0]:
        wins_array[6] =+ 1
    else:
        wins_array[9] =+ 1
    
    #Kevin vs. Tommy
    if scores_array[0][0] > scores_array[1][0]:
        wins_array[0] =+ 1
    else:
        wins_array[1] =+ 1
        
    return wins_array

In [53]:
def week2(scores_array, wins_array):
    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6, 'Eli':7, 
             'Brand':8, 'Cam':9, 'Burnett':10, 
             'Mike': 11} #not used, just for reference

    
    #Brenton vs. Tommy
    if scores_array[5][1] > scores_array[1][1]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[1]= wins_array[1] + 1
    
    #Mike vs. Will    
    if scores_array[11][1] > scores_array[3][1]:
        wins_array[11] = wins_array[11]+ 1
    else:
        wins_array[3] = wins_array[3]+ 1
    
    #Wolf vs. Todd
    if scores_array[4][1] > scores_array[6][1]:
        wins_array[4] = wins_array[4] + 1
    else:
        wins_array[6] = wins_array[6]+ 1
        
    #Jay vs. Brand
    if scores_array[2][1] > scores_array[8][1]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[8] = wins_array[8]+ 1
    
    #Eli vs. Kevin
    if scores_array[7][1] > scores_array[0][1]:
        wins_array[7] = wins_array[7]+ 1
    else:
        wins_array[0] = wins_array[0]+ 1
    
    #Cam vs. Burnett
    if scores_array[9][1] > scores_array[10][1]:
        wins_array[9] = wins_array[9] + 1
    else:
        wins_array[10] = wins_array[10] + 1
    return wins_array

In [54]:
def week3(scores_array, wins_array):
    
    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6, 'Eli':7, 
             'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference

    #Brenton vs. Eli
    if scores_array[5][2] > scores_array[7][2]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[7] = wins_array[7] + 1
    
    #Mike vs. Jay    
    if scores_array[11][2] > scores_array[2][2]:
        wins_array[11] = wins_array[11] + 1
    else:
        wins_array[2] = wins_array[2] + 1
    
    #Will vs. Burnett
    if scores_array[3][2] > scores_array[10][2]:
        wins_array[3] = wins_array[3] + 1
    else:
        wins_array[10] = wins_array[10] + 1
        
    #Wolf vs. Cam
    if scores_array[4][2] > scores_array[9][2]:
        wins_array[4] = wins_array[4] + 1
    else:
        wins_array[9] = wins_array[9] + 1
    
    #Todd vs. Kevin
    if scores_array[6][2] > scores_array[0][2]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[0] = wins_array[0] + 1
    
    #Tommy vs. Brand
    if scores_array[1][2] > scores_array[8][2]:
        wins_array[1] = wins_array[1] + 1
    else:
        wins_array[8] = wins_array[8] + 1
    return wins_array

In [55]:
def week4(scores_array, wins_array):
    
    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6,'Eli':7, 
             'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference

    
    #Brenton vs. Todd
    if scores_array[5][3] > scores_array[6][3]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[6] = wins_array[6] + 1
    
    #Mike vs. Tommy    
    if scores_array[11][3] > scores_array[1][3]:
        wins_array[11] = wins_array[11] + 1
    else:
        wins_array[1] = wins_array[1] + 1
    
    #Will vs. Jay
    if scores_array[3][3] > scores_array[2][3]:
        wins_array[3] = wins_array[3] + 1
    else:
        wins_array[2] = wins_array[2] + 1
           
    #Wolf vs. Burnett
    if scores_array[4][3] > scores_array[10][3]:
        wins_array[4] = wins_array[4] + 1
    else:
        wins_array[10] = wins_array[10] + 1
    
    #Eli vs. Brand
    if scores_array[7][3] > scores_array[8][3]:
        wins_array[7] = wins_array[7] + 1
    else:
        wins_array[8] = wins_array[8] + 1

    #Cam vs. Kevin
    if scores_array[9][3] > scores_array[0][3]:
        wins_array[9] = wins_array[9] + 1
    else:
        wins_array[0] = wins_array[0] + 1
        
    return wins_array

In [56]:
def week5(scores_array, wins_array):
    
    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6, 'Eli':7, 
             'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference

    #Brenton vs. Cam
    if scores_array[5][4] > scores_array[9][4]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[9] = wins_array[9] + 1
    
    #Jay vs. Burnett    
    if scores_array[2][4] > scores_array[10][4]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[10] = wins_array[10] + 1
    
    #Todd vs. Brand
    if scores_array[6][4] > scores_array[8][4]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[8] = wins_array[8] + 1
           
    #Kevin vs. Wolf
    if scores_array[0][4] > scores_array[4][4]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[4] = wins_array[4] + 1
    
    #Will vs. Tommy
    if scores_array[3][4] > scores_array[1][4]:
        wins_array[3] = wins_array[3] + 1
    else:
        wins_array[1] = wins_array[1] + 1

    #Eli vs. Mike
    if scores_array[7][4] > scores_array[11][4]:
        wins_array[7] = wins_array[7] + 1
    else:
        wins_array[11] = wins_array[11] + 1
        
    return wins_array

In [57]:
def week6(scores_array, wins_array):

    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6,'Eli':7,
             'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference

    #Brenton vs. Wolf
    if scores_array[5][5] > scores_array[4][5]:
        wins_array[5] = wins_array[5]+ 1
    else:
        wins_array[4] = wins_array[4]+ 1
    
    #Jay vs. Tommy    
    if scores_array[2][5] > scores_array[1][5]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[1] = wins_array[1] + 1
    
    #Cam vs. Brand
    if scores_array[9][5] > scores_array[8][5]:
        wins_array[9] = wins_array[9]+ 1
    else:
        wins_array[8] = wins_array[8]+ 1
           
    #Eli vs. Will
    if scores_array[7][5] > scores_array[3][5]:
        wins_array[7] = wins_array[7] + 1
    else:
        wins_array[3] = wins_array[3] + 1
    
    #Kevin vs. Burnett
    if scores_array[0][5] > scores_array[10][5]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[10] = wins_array[10] + 1

    #Todd vs. Mike
    if scores_array[6][5] > scores_array[11][5]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[11] = wins_array[11] + 1
        
    return wins_array

In [58]:
def week7(scores_array, wins_array):

    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6,'Eli':7,
             'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference

    #Brenton vs. Kevin
    if scores_array[5][6] > scores_array[0][6]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[0] = wins_array[0] + 1
    
    #Mike vs. Cam    
    if scores_array[11][6] > scores_array[9][6]:
        wins_array[11] = wins_array[11] + 1
    else:
        wins_array[9] = wins_array[9] + 1
    
    #Will vs. Todd
    if scores_array[3][6] > scores_array[6][6]:
        wins_array[3] = wins_array[3] + 1
    else:
        wins_array[6] = wins_array[6] + 1
           
    #Wolf vs. Brand
    if scores_array[4][6] > scores_array[8][6]:
        wins_array[4] = wins_array[4] + 1
    else:
        wins_array[8] = wins_array[8] + 1
    
    #Jay vs. Eli
    if scores_array[2][6] > scores_array[7][6]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[7] = wins_array[7] + 1

    #Tommy vs. Burnett
    if scores_array[1][6] > scores_array[10][6]:
        wins_array[1] = wins_array[1] + 1
    else:
        wins_array[10] = wins_array[10] + 1
        
    return wins_array

In [59]:
def week8(scores_array, wins_array):
    
    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6,'Eli':7, 
             'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference

    #Brenton vs. Burnett
    if scores_array[5][7] > scores_array[10][7]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[10] = wins_array[10] + 1
    
    #Mike vs. Wolf    
    if scores_array[11][7] > scores_array[4][7]:
        wins_array[11] = wins_array[11] + 1
    else:
        wins_array[4] = wins_array[4] + 1
    
    #Will vs. Cam
    if scores_array[3][7] > scores_array[9][7]:
        wins_array[3] = wins_array[3] + 1
    else:
        wins_array[9] = wins_array[9] + 1
           
    #Todd vs. Jay
    if scores_array[6][7] > scores_array[2][7]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[2] = wins_array[2] + 1
    
    #Eli vs. Tommy
    if scores_array[7][7] > scores_array[1][7]:
        wins_array[7] = wins_array[7] + 1
    else:
        wins_array[1] = wins_array[1] + 1

    #Kevin vs. Brand
    if scores_array[0][7] > scores_array[8][7]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[8] = wins_array[8]+ 1
        
    return wins_array

In [60]:
def week9(scores_array, wins_array):

    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6,'Eli':7, 
             'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference

    #Brenton vs. Brand
    if scores_array[5][8] > scores_array[8][8]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[8] = wins_array[8] + 1
    
    #Mike vs. Kevin    
    if scores_array[11][8] > scores_array[0][8]:
        wins_array[11] = wins_array[11] + 1
    else:
        wins_array[0] = wins_array[0] + 1
    
    #Will vs. Wolf
    if scores_array[3][8] > scores_array[4][8]:
        wins_array[3] = wins_array[3] + 1
    else:
        wins_array[4] = wins_array[4] + 1
           
    #Todd vs. Tommy
    if scores_array[6][8] > scores_array[1][8]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[1] = wins_array[1] + 1
    
    #Jay vs. Cam
    if scores_array[2][8] > scores_array[9][8]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[9] = wins_array[9] + 1

    #Eli vs. Burnett
    if scores_array[7][8] > scores_array[10][8]:
        wins_array[7] = wins_array[7] + 1
    else:
        wins_array[10] = wins_array[10] + 1
        
    return wins_array

In [61]:
def week10(scores_array, wins_array):
    
    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6,'Eli':7, 
             'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference

    #Brenton vs. Mike
    if scores_array[5][9] > scores_array[11][9]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[11] = wins_array[11] + 1
    
    #Will vs. Kevin    
    if scores_array[3][9] > scores_array[0][9]:
        wins_array[3] = wins_array[3] + 1
    else:
        wins_array[0] = wins_array[0] + 1
    
    #Wolf vs. Jay
    if scores_array[4][9] > scores_array[2][9]:
        wins_array[4] = wins_array[4]+ 1
    else:
        wins_array[2] = wins_array[2]+ 1
           
    #Todd vs. Eli
    if scores_array[6][9] > scores_array[7][9]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[7] = wins_array[7] + 1
    
    #Cam vs. Tommy
    if scores_array[9][9] > scores_array[1][9]:
        wins_array[9] = wins_array[9] + 1
    else:
        wins_array[1] = wins_array[1] + 1

    #Burnett vs. Brand
    if scores_array[10][9] > scores_array[8][9]:
        wins_array[10] = wins_array[10] + 1
    else:
        wins_array[8] = wins_array[8] + 1
        
    return wins_array

In [62]:
def week11(scores_array, wins_array):

    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6,'Eli':7, 
             'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference

    #Brenton vs. Will
    if scores_array[5][10] > scores_array[3][10]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[3] = wins_array[3] + 1
    
    #Mike vs. Brand    
    if scores_array[11][10] > scores_array[8][10]:
        wins_array[11] = wins_array[11]+ 1
    else:
        wins_array[8] = wins_array[8] + 1
    
    #Wolf vs. Tommy
    if scores_array[4][10] > scores_array[1][10]:
        wins_array[4] = wins_array[4] + 1
    else:
        wins_array[1] = wins_array[1] + 1
           
    #Todd vs. Burnett
    if scores_array[6][10] > scores_array[10][10]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[10] = wins_array[10] + 1
    
    #Jay vs. Kevin
    if scores_array[2][10] > scores_array[0][10]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[0] = wins_array[0]+ 1

    #Eli vs. Cam
    if scores_array[7][10] > scores_array[9][10]:
        wins_array[7] = wins_array[7] + 1
    else:
        wins_array[9] = wins_array[9] + 1
        
    return wins_array

In [63]:
def week12(scores_array, wins_array):
    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 'Wolf':4, 'Brenton':5, 'Todd':6,
            'Eli':7, 'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference
    
    #Brenton vs. Jay
    if scores_array[5][11] > scores_array[2][11]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[2] = wins_array[2] + 1
    
    #Mike vs. Burnett   
    if scores_array[11][11] > scores_array[10][11]:
        wins_array[11] = wins_array[11] + 1
    else:
        wins_array[10] = wins_array[10] + 1
    
    #Will vs. Brand
    if scores_array[3][11] > scores_array[8][11]:
        wins_array[3] = wins_array[3]+ 1
    else:
        wins_array[8] = wins_array[8] + 1
        
    #Wolf vs. Eli
    if scores_array[4][11] > scores_array[7][11]:
        wins_array[4] = wins_array[4] + 1
    else:
        wins_array[7] = wins_array[7] + 1
        
    #Todd vs. Cam
    if scores_array[6][11] > scores_array[9][11]:
        wins_array[6] = wins_array[6]+ 1
    else:
        wins_array[9] = wins_array[9]+ 1
    
    #Kevin vs. Tommy
    if scores_array[0][11] > scores_array[1][11]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[1] = wins_array[1] + 1
        
    return wins_array

In [64]:
def week13(scores_array, wins_array):
    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6, 'Eli':7, 
             'Brand':8, 'Cam':9, 'Burnett':10, 
             'Mike': 11} #not used, just for reference

    
    #Brenton vs. Tommy
    if scores_array[5][12] > scores_array[1][12]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[1]= wins_array[1] + 1
    
    #Mike vs. Will    
    if scores_array[11][12] > scores_array[3][12]:
        wins_array[11] = wins_array[11]+ 1
    else:
        wins_array[3] = wins_array[3]+ 1
    
    #Wolf vs. Todd
    if scores_array[4][12] > scores_array[6][12]:
        wins_array[4] = wins_array[4] + 1
    else:
        wins_array[6] = wins_array[6]+ 1
        
    #Jay vs. Brand
    if scores_array[2][12] > scores_array[8][12]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[8] = wins_array[8]+ 1
    
    #Eli vs. Kevin
    if scores_array[7][12] > scores_array[0][12]:
        wins_array[7] = wins_array[7]+ 1
    else:
        wins_array[0] = wins_array[0]+ 1
    
    #Cam vs. Burnett
    if scores_array[9][12] > scores_array[10][12]:
        wins_array[9] = wins_array[9] + 1
    else:
        wins_array[10] = wins_array[10] + 1
    return wins_array

In [65]:
def week14(scores_array, wins_array):
    
    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6, 'Eli':7, 
             'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference

    #Brenton vs. Eli
    if scores_array[5][13] > scores_array[7][13]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[7] = wins_array[7] + 1
    
    #Mike vs. Jay    
    if scores_array[11][13] > scores_array[2][13]:
        wins_array[11] = wins_array[11] + 1
    else:
        wins_array[2] = wins_array[2] + 1
    
    #Will vs. Burnett
    if scores_array[3][13] > scores_array[10][13]:
        wins_array[3] = wins_array[3] + 1
    else:
        wins_array[10] = wins_array[10] + 1
        
    #Wolf vs. Cam
    if scores_array[4][13] > scores_array[9][13]:
        wins_array[4] = wins_array[4] + 1
    else:
        wins_array[9] = wins_array[9] + 1
    
    #Todd vs. Kevin
    if scores_array[6][13] > scores_array[0][13]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[0] = wins_array[0] + 1
    
    #Tommy vs. Brand
    if scores_array[1][13] > scores_array[8][13]:
        wins_array[1] = wins_array[1] + 1
    else:
        wins_array[8] = wins_array[8] + 1
    return wins_array

In [66]:
def week15(scores_array, wins_array):
    
    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 
             'Wolf':4, 'Brenton':5, 'Todd':6,'Eli':7, 
             'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference

    
    #Brenton vs. Todd
    if scores_array[5][14] > scores_array[6][14]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[6] = wins_array[6] + 1
    
    #Mike vs. Tommy    
    if scores_array[11][14] > scores_array[1][14]:
        wins_array[11] = wins_array[11] + 1
    else:
        wins_array[1] = wins_array[1] + 1
    
    #Will vs. Jay
    if scores_array[3][14] > scores_array[2][14]:
        wins_array[3] = wins_array[3] + 1
    else:
        wins_array[2] = wins_array[2] + 1
           
    #Wolf vs. Burnett
    if scores_array[4][14] > scores_array[10][14]:
        wins_array[4] = wins_array[4] + 1
    else:
        wins_array[10] = wins_array[10] + 1
    
    #Eli vs. Brand
    if scores_array[7][14] > scores_array[8][14]:
        wins_array[7] = wins_array[7] + 1
    else:
        wins_array[8] = wins_array[8] + 1

    #Cam vs. Kevin
    if scores_array[9][14] > scores_array[0][14]:
        wins_array[9] = wins_array[9] + 1
    else:
        wins_array[0] = wins_array[0] + 1
        
    return wins_array

In [67]:
def week_fair(scores_array, wins_array, week = 12):
    
    Teams = {'Kevin':0, 'Tommy':1, 'Jay':2, 'Will':3, 'Wolf':4, 'Brenton':5, 'Todd':6,
            'Eli':7, 'Brand':8, 'Cam':9, 'Burnett':10, 'Mike': 11} #not used, just for reference

    p = np.arange(12)
    random.shuffle(p)
    
    for n in range(6):
        first = p[2*n]
        second = p[2*n+1]
    
        if scores_array[first][week-1] > scores_array[second][week-1]:
            wins_array[first] = wins_array[first] + 1
        else:
            wins_array[second] = wins_array[second] + 1
    
    return wins_array

In [68]:
def simulate_one_season_matchups(scoring_array, fair=False):
    wins_array = np.zeros(12)
    WINS1 = week1(scoring_array, wins_array.copy())
    WINS2 = week2(scoring_array, WINS1.copy())
    WINS3 = week3(scoring_array, WINS2.copy())
    WINS4 = week4(scoring_array, WINS3.copy())
    WINS5 = week5(scoring_array, WINS4.copy())
    WINS6 = week6(scoring_array, WINS5.copy())
    WINS7 = week7(scoring_array, WINS6.copy())
    WINS8 = week8(scoring_array, WINS7.copy())
    WINS9 = week9(scoring_array, WINS8.copy())
    WINS10 = week10(scoring_array, WINS9.copy())
    WINS11 = week11(scoring_array, WINS10.copy())
        
    if fair==False:
        WINS12 = week12(scoring_array, WINS11.copy())
        WINS13 = week13(scoring_array, WINS12.copy())
        WINS14 = week14(scoring_array, WINS13.copy())
        wins_per_team = tuple(week15(scoring_array, WINS14.copy()))
    elif fair==True:
        WINS12 = week_fair(scoring_array, WINS11.copy(), week=12)
        WINS13 = week_fair(scoring_array, WINS12.copy(), week=13)
        WINS14 = week_fair(scoring_array, WINS13.copy(), week=14)
        wins_per_team = tuple(week_fair(scoring_array, WINS14.copy(), week=15))
        
    #return final results
    losses_per_team = tuple([15-w for w in wins_per_team])
    score_per_team = tuple(scoring_array.sum(axis=1))
    label_per_team =  tuple(FF_2023_summary['Team_Name'])
    standings = pd.DataFrame(np.vstack((wins_per_team, losses_per_team, score_per_team)).T, index=label_per_team)
    standings = standings.rename(columns={0:'W', 1:'L', 2:'Pts'})    
    
    standings['Pts'] = standings['Pts'].astype(float)
    standings = standings.sort_values(by=['W', 'Pts'], ascending=[False, False])
    
    standings['Place'] = np.arange(1,13)
    standings['Playoffs'] = np.where(standings['Place'] < 5, 1, 0)
    standings['Top'] = np.where(standings['Place'] == 1, 1, 0)
    standings['Sacko'] = np.where(standings['Place'] > 11, 1, 0)
    
    places = np.array(standings['Place'])
    playoffs = np.array(standings['Playoffs'])
    tops = np.array(standings['Top'])
    sackos = np.array(standings['Sacko'])
    
    return standings

In [69]:
def simulate_many_seasons(FF_summary, sims = 2, fair=False):
    '''
    @sims is the number of simulations you would like to run.
    '''
    SCORES = simulate_one_season_scores(FF_summary)
    TOTAL = simulate_one_season_matchups(SCORES, fair=fair)
    
    for i in range(1,sims):
            
        SCORES = simulate_one_season_scores(FF_summary)
        SEASON_DF = simulate_one_season_matchups(SCORES, fair=fair)
        
        for col in TOTAL.columns.values:
            TOTAL[col] = TOTAL[col]/(i+1)*i + SEASON_DF[col]/(i+1) #Average is continuously updated across trials
    return TOTAL

def clean_total(total):
    total['W'] = round(total['W'], 2)
    total['L'] = 15-total['W']
    total['Pts'] = round(total['Pts'], 2)
    total['Place'] = round(total['Place'], 2)
    total['Playoffs'] = round(total['Playoffs'], 3)*100
    total['Top'] = round(total['Top'], 3)*100
    total['Sacko'] = round(total['Sacko'], 3)*100
    total = total.sort_values(by='Place')
    return total

# Run simulations

In [70]:
Sims = simulate_many_seasons(FF_2023_summary, sims = 10000)
Sims = clean_total(Sims)

In [71]:
print(sum(Sims['W']), sum(Sims['L']))
Sims

89.99 90.01000000000002

                              W     L      Pts  Place  Playoffs   Top  Sacko
Sackwash Lyfe              9.49  5.51  1833.88   3.53      70.4  22.6    0.2
Brady really was washed…   9.40  5.60  1827.41   3.66      68.4  20.8    0.2
Gee Whiz Darnell           9.36  5.64  1826.17   3.71      67.5  20.3    0.2
Mr. Fans Noodle Haus       9.11  5.89  1801.04   4.08      61.4  15.6    0.4
PurpleVector Reunion Tour  8.87  6.13  1798.50   4.36      57.1  13.3    0.5
Schmaap                    7.62  7.38  1700.95   6.33      26.5   3.3    2.9
2 Movin' 2 Up              7.37  7.63  1682.82   6.73      22.6   2.3    3.8
Alternative Hypothesis     5.97  9.03  1588.80   8.82       6.3   0.5   14.7
Pierogi Night              5.89  9.11  1593.80   8.91       6.2   0.5   15.7
GOBias Industries          5.84  9.16  1594.92   8.94       6.0   0.4   15.9
Herbin Legends             5.69  9.31  1562.64   9.25       4.7   0.3   19.6
Pay Dirt & Pylons III      5.38  9.62  1538.29   9.69       3.0   0.1   25.9

In [34]:
Sims.to_excel('SimsRegular23.xlsx')

In [72]:
Sims2 = simulate_many_seasons(FF_2023_summary, sims = 10000, fair=True)
Sims2 = clean_total(Sims2)

In [73]:
print(sum(Sims2['W']), sum(Sims2['L']))
Sims2

90.0 90.0

                              W     L      Pts  Place  Playoffs   Top  Sacko
Sackwash Lyfe              9.35  5.65  1832.71   3.63      69.0  21.5    0.2
Brady really was washed…   9.28  5.72  1827.55   3.71      67.9  20.4    0.3
Gee Whiz Darnell           9.19  5.81  1823.95   3.85      65.4  19.0    0.4
Mr. Fans Noodle Haus       8.95  6.05  1801.18   4.22      59.5  15.7    0.6
PurpleVector Reunion Tour  8.90  6.10  1799.40   4.31      57.3  14.9    0.5
Schmaap                    7.57  7.43  1700.71   6.40      27.1   3.8    3.3
2 Movin' 2 Up              7.32  7.68  1682.11   6.80      22.7   2.6    4.1
Pierogi Night              6.14  8.86  1595.38   8.65       8.1   0.6   14.2
GOBias Industries          6.13  8.87  1595.65   8.66       7.9   0.6   14.0
Alternative Hypothesis     6.04  8.96  1588.35   8.81       6.6   0.5   14.8
Herbin Legends             5.70  9.30  1562.94   9.30       4.9   0.3   21.1
Pay Dirt & Pylons III      5.43  9.57  1538.87   9.66       3.7   0.2   26.5

In [37]:
Sims2.to_excel('SimsRandom23.xlsx')