In [4]:
import pandas as pd
import numpy as np
import random
pd.set_option('display.max_columns', None)

In [5]:
FF_2022 = pd.read_excel('FF_2022.xlsx')
FF_2022_summary = FF_2022[['Team_Name', 'Mean']].drop(12, 0)

In [6]:
FF_2022_summary

                    Team_Name        Mean
0            Gee Whiz Darnell  116.717333
1             Null Hypothesis  114.701333
2               Pierogi Night  113.794667
3                Movin' On Up  110.230667
4   PurpleVector Reunion Tour  109.345333
5           GOBias Industries  118.160000
6        Brady = Washed Up IV  116.488000
7        Pay Dirt & Pylons II  113.424000
8               Sackwash Lyfe  108.116000
9        Mr. Fans Noodle Haus  101.810667
10       Jasjaap's Primo Team  104.830667
11                     Schmop  102.232000

In [7]:
std = 22
games = 15

def simulate_one_season_scores(df):
    Brenton_scores = np.random.normal(df.loc[0, 'Mean'], std, games)
    Eli_scores = np.random.normal(df.loc[1, 'Mean'], std, games)
    Mike_scores = np.random.normal(df.loc[2, 'Mean'], std, games)
    Todd_scores = np.random.normal(df.loc[3, 'Mean'], std, games)
    Kevin_scores = np.random.normal(df.loc[4, 'Mean'], std, games)
    Wolf_scores = np.random.normal(df.loc[5, 'Mean'], std, games)
    Will_scores = np.random.normal(df.loc[6, 'Mean'], std, games)
    Cam_scores = np.random.normal(df.loc[7, 'Mean'], std, games)
    Tommy_scores = np.random.normal(df.loc[8, 'Mean'], std, games)
    Jay_scores = np.random.normal(df.loc[9, 'Mean'], std, games)
    Jasjaap_scores = np.random.normal(df.loc[10, 'Mean'], std, games)
    Burnett_scores = np.random.normal(df.loc[11, 'Mean'], std, games)
    
    SCORES = np.array([Brenton_scores, Eli_scores, Mike_scores, Todd_scores, 
                       Kevin_scores, Wolf_scores, Will_scores, Cam_scores, 
                       Tommy_scores, Jay_scores, Jasjaap_scores, Burnett_scores])
    return(SCORES)

In [8]:
simulate_one_season_scores(FF_2022_summary)

array([[ 119.43005438,  121.5900363 ,  125.28146305,  113.27816668,
         152.28954202,  135.08337121,  101.39119799,  136.45354396,
         154.95040823,  115.89704349,  115.91583506,  113.48547993,
         143.8344663 ,   92.67210785,   95.17810989],
       [  70.59739254,  139.29422072,  105.99377698,   86.2745567 ,
         114.42652193,  126.84915824,  130.66182393,   93.21062046,
         109.90437957,   98.74919095,  103.76311907,   89.97578619,
          64.51385761,   91.88356168,  104.12909268],
       [  71.41426503,   99.79425507,  109.91005141,  114.27212239,
         116.70063098,   92.54176422,  140.91147935,  128.24941139,
         121.99795381,  128.68411095,  100.78907162,  104.64741787,
         111.83412785,   80.3081583 ,   88.70700017],
       [ 121.37010564,  130.33925693,   52.48378138,  100.95456499,
         112.86442403,  153.03088452,   86.06916811,   94.79362757,
          91.3625011 ,  129.44664811,   83.99878462,  140.41173111,
          97.19000468,   80.69108248,  122.17265036],
       [ 112.80228919,  101.29282141,   89.20957784,  146.98810576,
         103.93645438,  116.64682854,  110.61930259,   93.48488639,
         103.2854126 ,  123.80872762,   59.61139471,   86.89406121,
         143.17674741,  122.83028982,  127.00812082],
       [ 100.15650071,  130.21775642,  105.78250433,  113.29036162,
         101.52182292,  118.88438399,  134.62850055,  105.51710931,
         133.80121901,   90.34828069,  136.49950317,  119.81130526,
          93.75966615,  150.83898074,  105.79412373],
       [  92.30163553,  160.04445237,  125.64003291,  144.96688716,
         149.08471042,  125.26344122,   86.39056597,  117.1815425 ,
         110.45448913,   82.41720394,  128.13756809,  129.05433681,
          98.1099225 ,  111.46226011,   95.02937619],
       [  82.63469195,  131.4657094 ,  107.3279368 ,  108.03243123,
          99.24336342,  107.3474566 ,  116.51259066,  124.83419439,
          96.87691111,  141.05135926,  122.7775795 ,   69.15039061,
          95.24948752,  115.39241262,  115.30939005],
       [ 136.69958488,   98.23549317,   78.66382265,  150.89573015,
         120.36044704,  120.37873713,  128.16886307,  115.95967003,
          92.68596732,  161.53049096,   94.66551268,  135.07907155,
         129.35685745,  122.33312138,   64.35493442],
       [ 111.6187337 ,  122.85201043,   36.37818802,   84.18867247,
         126.13359971,  106.83579909,   87.99944986,  107.62346633,
          84.98550537,  119.53408305,  113.66591875,   81.08939883,
          85.86204174,  126.77480554,  134.67579445],
       [  85.49046621,   86.53832998,   86.60331652,   85.43039672,
         125.18949132,  118.98371133,  125.35741322,  115.86548412,
          81.66477894,   93.06664811,  115.30484812,  123.05990044,
         103.02226814,   79.29016233,   87.18867959],
       [ 126.35399479,  104.1650755 ,   86.87581918,  109.31966075,
         127.26388622,   76.12079931,  103.98316568,   78.56434946,
         100.27641462,  108.5641995 ,  143.25158512,  111.04668821,
         109.96063223,   92.78415293,  105.10983266]])

In [9]:
def week1(scores_array, wins_array):
    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 'Kevin':4, 'Wolf':5, 'Will':6,
            'Cam':7, 'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Eli
    if scores_array[0][0] > scores_array[1][0]:
        wins_array[0] =+ 1
    else:
        wins_array[1] =+ 1
    
    #Mike vs. Burnett    
    if scores_array[2][0] > scores_array[11][0]:
        wins_array[2] =+ 1
    else:
        wins_array[11] =+ 1
    
    #Wolf vs. Jasjaap
    if scores_array[5][0] > scores_array[10][0]:
        wins_array[5] =+ 1
    else:
        wins_array[10] =+ 1
        
    #Jay vs. Tommy
    if scores_array[9][0] > scores_array[8][0]:
        wins_array[9] =+ 1
    else:
        wins_array[8] =+ 1
        
    #Will vs. Cam
    if scores_array[6][0] > scores_array[7][0]:
        wins_array[6] =+ 1
    else:
        wins_array[7] =+ 1
    
    #Todd vs. Kevin
    if scores_array[3][0] > scores_array[4][0]:
        wins_array[3] =+ 1
    else:
        wins_array[4] =+ 1
        
    return wins_array

In [10]:
def week2(scores_array, wins_array):
    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6,'Cam':7,
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Jay
    if scores_array[0][1] > scores_array[9][1]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[9]= wins_array[9] + 1
    
    #Mike vs. Eli    
    if scores_array[2][1] > scores_array[1][1]:
        wins_array[2] = wins_array[2]+ 1
    else:
        wins_array[1] = wins_array[1]+ 1
    
    #Wolf vs. Todd
    if scores_array[5][1] > scores_array[3][1]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[3] = wins_array[3]+ 1
        
    #Jasjaap vs. Will
    if scores_array[10][1] > scores_array[6][1]:
        wins_array[10] = wins_array[10] + 1
    else:
        wins_array[6] = wins_array[6]+ 1
    
    #Cam vs. Burnett
    if scores_array[7][1] > scores_array[11][1]:
        wins_array[7] = wins_array[7]+ 1
    else:
        wins_array[11] = wins_array[11]+ 1
    
    #Tommy vs. Kevin
    if scores_array[8][1] > scores_array[4][1]:
        wins_array[8] = wins_array[8] + 1
    else:
        wins_array[4] = wins_array[4] + 1
    return wins_array

In [11]:
def week3(scores_array, wins_array):
    
    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6,'Cam':7, 
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Kevin
    if scores_array[0][2] > scores_array[4][2]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[4] = wins_array[4] + 1
    
    #Mike vs. Jay    
    if scores_array[2][2] > scores_array[9][2]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[9] = wins_array[9] + 1
    
    #Wolf vs. Tommy
    if scores_array[5][2] > scores_array[8][2]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[8] = wins_array[8] + 1
        
    #Jasjaap vs. Todd
    if scores_array[10][2] > scores_array[3][2]:
        wins_array[10] = wins_array[10] + 1
    else:
        wins_array[3] = wins_array[3] + 1
    
    #Eli vs. Cam
    if scores_array[1][2] > scores_array[7][2]:
        wins_array[1] = wins_array[1] + 1
    else:
        wins_array[7] = wins_array[7] + 1
    
    #Will vs. Burnett
    if scores_array[6][2] > scores_array[11][2]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[11] = wins_array[11] + 1
    return wins_array

In [12]:
def week4(scores_array, wins_array):
    
    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6,'Cam':7, 
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Wolf
    if scores_array[0][3] > scores_array[5][3]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[5] = wins_array[5] + 1
    
    #Mike vs. Kevin    
    if scores_array[2][3] > scores_array[4][3]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[4] = wins_array[4] + 1
    
    #Jasjaap vs. Burnett
    if scores_array[10][3] > scores_array[11][3]:
        wins_array[10] = wins_array[10] + 1
    else:
        wins_array[11] = wins_array[11] + 1
           
    #Eli vs. Will
    if scores_array[1][3] > scores_array[6][3]:
        wins_array[1] = wins_array[1] + 1
    else:
        wins_array[6] = wins_array[6] + 1
    
    #Jay vs. Cam
    if scores_array[9][3] > scores_array[7][3]:
        wins_array[9] = wins_array[9] + 1
    else:
        wins_array[7] = wins_array[7] + 1

    #Tommy vs. Todd
    if scores_array[8][3] > scores_array[3][3]:
        wins_array[8] = wins_array[8] + 1
    else:
        wins_array[3] = wins_array[3] + 1
        
    return wins_array

In [13]:
def week5(scores_array, wins_array):
    
    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6, 'Cam':7, 
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Todd
    if scores_array[0][4] > scores_array[3][4]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[3] = wins_array[3] + 1
    
    #Mike vs. Wolf    
    if scores_array[2][4] > scores_array[5][4]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[5] = wins_array[5] + 1
    
    #Jasjaap vs. Tommy
    if scores_array[10][4] > scores_array[8][4]:
        wins_array[10] = wins_array[10] + 1
    else:
        wins_array[8] = wins_array[8] + 1
           
    #Eli vs. Burnett
    if scores_array[1][4] > scores_array[11][4]:
        wins_array[1] = wins_array[1] + 1
    else:
        wins_array[11] = wins_array[11] + 1
    
    #Jay vs. Will
    if scores_array[9][4] > scores_array[6][4]:
        wins_array[9] = wins_array[9] + 1
    else:
        wins_array[6] = wins_array[6] + 1

    #Cam vs. Kevin
    if scores_array[7][4] > scores_array[4][4]:
        wins_array[7] = wins_array[7] + 1
    else:
        wins_array[4] = wins_array[4] + 1
        
    return wins_array

In [14]:
def week6(scores_array, wins_array):

    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6,'Cam':7, 
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Tommy
    if scores_array[0][5] > scores_array[8][5]:
        wins_array[0] = wins_array[0]+ 1
    else:
        wins_array[8] = wins_array[8]+ 1
    
    #Mike vs. Todd    
    if scores_array[2][5] > scores_array[3][5]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[3] = wins_array[3] + 1
    
    #Wolf vs. Cam
    if scores_array[5][5] > scores_array[7][5]:
        wins_array[5] = wins_array[5]+ 1
    else:
        wins_array[7] = wins_array[7]+ 1
           
    #Jasjaap vs. Eli
    if scores_array[10][5] > scores_array[1][5]:
        wins_array[10] = wins_array[10] + 1
    else:
        wins_array[1] = wins_array[1] + 1
    
    #Jay vs. Burnett
    if scores_array[9][5] > scores_array[11][5]:
        wins_array[9] = wins_array[9] + 1
    else:
        wins_array[11] = wins_array[11] + 1

    #Will vs. Kevin
    if scores_array[6][5] > scores_array[4][5]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[4] = wins_array[4] + 1
        
    return wins_array

In [15]:
def week7(scores_array, wins_array):

    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6, 'Cam':7, 
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Jasjaap
    if scores_array[0][6] > scores_array[10][6]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[10] = wins_array[10] + 1
    
    #Mike vs. Tommy    
    if scores_array[2][6] > scores_array[8][6]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[8] = wins_array[8] + 1
    
    #Wolf vs. Will
    if scores_array[5][6] > scores_array[6][6]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[6] = wins_array[6] + 1
           
    #Eli vs. Jay
    if scores_array[1][6] > scores_array[9][6]:
        wins_array[1] = wins_array[1] + 1
    else:
        wins_array[9] = wins_array[9] + 1
    
    #Cam vs. Todd
    if scores_array[7][6] > scores_array[3][6]:
        wins_array[7] = wins_array[7] + 1
    else:
        wins_array[3] = wins_array[3] + 1

    #Burnett vs. Kevin
    if scores_array[11][6] > scores_array[4][6]:
        wins_array[11] = wins_array[11] + 1
    else:
        wins_array[4] = wins_array[4] + 1
        
    return wins_array

In [16]:
def week8(scores_array, wins_array):
    
    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6,'Cam':7, 
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Mike
    if scores_array[0][7] > scores_array[2][7]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[2] = wins_array[2] + 1
    
    #Wolf vs. Burnett    
    if scores_array[5][7] > scores_array[11][7]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[11] = wins_array[11] + 1
    
    #Jasjaap vs. Jay
    if scores_array[10][7] > scores_array[9][7]:
        wins_array[10] = wins_array[10] + 1
    else:
        wins_array[9] = wins_array[9] + 1
           
    #Eli vs. Kevin
    if scores_array[1][7] > scores_array[4][7]:
        wins_array[1] = wins_array[1] + 1
    else:
        wins_array[4] = wins_array[4] + 1
    
    #Will vs. Todd
    if scores_array[6][7] > scores_array[3][7]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[3] = wins_array[3] + 1

    #Cam vs. Tommy
    if scores_array[7][7] > scores_array[8][7]:
        wins_array[7] = wins_array[7] + 1
    else:
        wins_array[8] = wins_array[8]+ 1
        
    return wins_array

In [17]:
def week9(scores_array, wins_array):

    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6, 'Cam':7, 
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Cam
    if scores_array[0][8] > scores_array[7][8]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[7] = wins_array[7] + 1
    
    #Mike vs. Jasjaap    
    if scores_array[2][8] > scores_array[10][8]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[10] = wins_array[10] + 1
    
    #Wolf vs. Eli
    if scores_array[5][8] > scores_array[1][8]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[1] = wins_array[1] + 1
           
    #Jay vs. Kevin
    if scores_array[9][8] > scores_array[4][8]:
        wins_array[9] = wins_array[9] + 1
    else:
        wins_array[4] = wins_array[4] + 1
    
    #Will vs. Tommy
    if scores_array[6][8] > scores_array[8][8]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[8] = wins_array[8] + 1

    #Burnett vs. Todd
    if scores_array[11][8] > scores_array[3][8]:
        wins_array[11] = wins_array[11] + 1
    else:
        wins_array[3] = wins_array[3] + 1
        
    return wins_array

In [18]:
def week10(scores_array, wins_array):
    
    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6, 'Cam':7,
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Will
    if scores_array[0][9] > scores_array[6][9]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[6] = wins_array[6] + 1
    
    #Mike vs. Cam    
    if scores_array[2][9] > scores_array[7][9]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[7] = wins_array[7] + 1
    
    #Wolf vs. Jay
    if scores_array[5][9] > scores_array[9][9]:
        wins_array[5] = wins_array[5]+ 1
    else:
        wins_array[9] = wins_array[9]+ 1
           
    #Jasjaap vs. Kevin
    if scores_array[10][9] > scores_array[4][9]:
        wins_array[10] = wins_array[10] + 1
    else:
        wins_array[4] = wins_array[4] + 1
    
    #Eli vs. Todd
    if scores_array[1][9] > scores_array[3][9]:
        wins_array[1] = wins_array[1] + 1
    else:
        wins_array[3] = wins_array[3] + 1

    #Tommy vs. Burnett
    if scores_array[8][9] > scores_array[11][9]:
        wins_array[8] = wins_array[8] + 1
    else:
        wins_array[11] = wins_array[11] + 1
        
    return wins_array

In [28]:
def week11(scores_array, wins_array):

    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6, 'Cam':7,
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Burnett
    if scores_array[0][10] > scores_array[11][10]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[11] = wins_array[11] + 1
    
    #Mike vs. Will    
    if scores_array[2][10] > scores_array[6][10]:
        wins_array[2] = wins_array[2]+ 1
    else:
        wins_array[6] = wins_array[6] + 1
    
    #Wolf vs. Kevin
    if scores_array[5][10] > scores_array[4][10]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[4] = wins_array[4] + 1
           
    #Jasjaap vs. Cam
    if scores_array[10][10] > scores_array[7][10]:
        wins_array[10] = wins_array[10] + 1
    else:
        wins_array[7] = wins_array[7] + 1
    
    #Eli vs. Tommy
    if scores_array[1][10] > scores_array[8][10]:
        wins_array[1] = wins_array[1] + 1
    else:
        wins_array[8] = wins_array[8]+ 1

    #Jay vs. Todd
    if scores_array[9][10] > scores_array[3][10]:
        wins_array[9] = wins_array[9] + 1
    else:
        wins_array[3] = wins_array[3] + 1
        
    return wins_array

In [62]:
def week12(scores_array, wins_array):
    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 'Kevin':4, 'Wolf':5, 'Will':6,
            'Cam':7, 'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Eli
    if scores_array[0][11] > scores_array[1][11]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[1] = wins_array[1] + 1
    
    #Mike vs. Burnett    
    if scores_array[2][11] > scores_array[11][11]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[11] = wins_array[11] + 1
    
    #Wolf vs. Jasjaap
    if scores_array[5][11] > scores_array[10][11]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[10] = wins_array[10] + 1
        
    #Jay vs. Tommy
    if scores_array[9][11] > scores_array[8][11]:
        wins_array[9] = wins_array[9] + 1
    else:
        wins_array[8] = wins_array[8] + 1
        
    #Will vs. Cam
    if scores_array[6][11] > scores_array[7][11]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[7] = wins_array[7] + 1
    
    #Todd vs. Kevin
    if scores_array[3][11] > scores_array[4][11]:
        wins_array[3] = wins_array[3] + 1
    else:
        wins_array[4] = wins_array[4] + 1
        
    return wins_array

In [63]:
def week13(scores_array, wins_array):
    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6,'Cam':7,
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Jay
    if scores_array[0][12] > scores_array[9][12]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[9]= wins_array[9] + 1
    
    #Mike vs. Eli    
    if scores_array[2][12] > scores_array[1][12]:
        wins_array[2] = wins_array[2]+ 1
    else:
        wins_array[1] = wins_array[1]+ 1
    
    #Wolf vs. Todd
    if scores_array[5][12] > scores_array[3][12]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[3] = wins_array[3]+ 1
        
    #Jasjaap vs. Will
    if scores_array[10][12] > scores_array[6][12]:
        wins_array[10] = wins_array[10] + 1
    else:
        wins_array[6] = wins_array[6]+ 1
    
    #Cam vs. Burnett
    if scores_array[7][12] > scores_array[11][12]:
        wins_array[7] = wins_array[7]+ 1
    else:
        wins_array[11] = wins_array[11]+ 1
    
    #Tommy vs. Kevin
    if scores_array[8][12] > scores_array[4][12]:
        wins_array[8] = wins_array[8] + 1
    else:
        wins_array[4] = wins_array[4] + 1
    return wins_array

In [64]:
def week14(scores_array, wins_array):
    
    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6,'Cam':7, 
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Kevin
    if scores_array[0][13] > scores_array[4][13]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[4] = wins_array[4] + 1
    
    #Mike vs. Jay    
    if scores_array[2][13] > scores_array[9][13]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[9] = wins_array[9] + 1
    
    #Wolf vs. Tommy
    if scores_array[5][13] > scores_array[8][13]:
        wins_array[5] = wins_array[5] + 1
    else:
        wins_array[8] = wins_array[8] + 1
        
    #Jasjaap vs. Todd
    if scores_array[10][13] > scores_array[3][13]:
        wins_array[10] = wins_array[10] + 1
    else:
        wins_array[3] = wins_array[3] + 1
    
    #Eli vs. Cam
    if scores_array[1][13] > scores_array[7][13]:
        wins_array[1] = wins_array[1] + 1
    else:
        wins_array[7] = wins_array[7] + 1
    
    #Will vs. Burnett
    if scores_array[6][13] > scores_array[11][13]:
        wins_array[6] = wins_array[6] + 1
    else:
        wins_array[11] = wins_array[11] + 1
    return wins_array

In [65]:
def week15(scores_array, wins_array):
    
    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 
             'Kevin':4, 'Wolf':5, 'Will':6,'Cam':7, 
             'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    #Brenton vs. Wolf
    if scores_array[0][14] > scores_array[5][14]:
        wins_array[0] = wins_array[0] + 1
    else:
        wins_array[5] = wins_array[5] + 1
    
    #Mike vs. Kevin    
    if scores_array[2][14] > scores_array[4][14]:
        wins_array[2] = wins_array[2] + 1
    else:
        wins_array[4] = wins_array[4] + 1
    
    #Jasjaap vs. Burnett
    if scores_array[10][14] > scores_array[11][14]:
        wins_array[10] = wins_array[10] + 1
    else:
        wins_array[11] = wins_array[11] + 1
           
    #Eli vs. Will
    if scores_array[1][14] > scores_array[6][14]:
        wins_array[1] = wins_array[1] + 1
    else:
        wins_array[6] = wins_array[6] + 1
    
    #Jay vs. Cam
    if scores_array[9][14] > scores_array[7][14]:
        wins_array[9] = wins_array[9] + 1
    else:
        wins_array[7] = wins_array[7] + 1

    #Tommy vs. Todd
    if scores_array[8][14] > scores_array[3][14]:
        wins_array[8] = wins_array[8] + 1
    else:
        wins_array[3] = wins_array[3] + 1
        
    return wins_array

In [66]:
def week_fair(scores_array, wins_array, week = 12):
    Teams = {'Brenton':0, 'Eli':1, 'Mike':2, 'Todd':3, 'Kevin':4, 'Wolf':5, 'Will':6,
            'Cam':7, 'Tommy':8, 'Jay':9, 'Jasjaap':10, 'Burnett': 11} #not used, just for reference
    
    p = np.arange(12)
    random.shuffle(p)
    
    for n in range(6):
        first = p[2*n]
        second = p[2*n+1]
    
        if scores_array[first][week-1] > scores_array[second][week-1]:
            wins_array[first] = wins_array[first] + 1
        else:
            wins_array[second] = wins_array[second] + 1
    
    return wins_array

In [71]:
def simulate_one_season_matchups(scoring_array, fair=False):
    wins_array = np.zeros(12)
    WINS1 = week1(scoring_array, wins_array.copy())
    WINS2 = week2(scoring_array, WINS1.copy())
    WINS3 = week3(scoring_array, WINS2.copy())
    WINS4 = week4(scoring_array, WINS3.copy())
    WINS5 = week5(scoring_array, WINS4.copy())
    WINS6 = week6(scoring_array, WINS5.copy())
    WINS7 = week7(scoring_array, WINS6.copy())
    WINS8 = week8(scoring_array, WINS7.copy())
    WINS9 = week9(scoring_array, WINS8.copy())
    WINS10 = week10(scoring_array, WINS9.copy())
    WINS11 = week11(scoring_array, WINS10.copy())
        
    if fair==False:
        WINS12 = week12(scoring_array, WINS11.copy())
        WINS13 = week13(scoring_array, WINS12.copy())
        WINS14 = week14(scoring_array, WINS13.copy())
        wins_per_team = tuple(week15(scoring_array, WINS14.copy()))
    elif fair==True:
        WINS12 = week_fair(scoring_array, WINS11.copy(), week=12)
        WINS13 = week_fair(scoring_array, WINS12.copy(), week=13)
        WINS14 = week_fair(scoring_array, WINS13.copy(), week=14)
        wins_per_team = tuple(week_fair(scoring_array, WINS14.copy(), week=15))
        
    #return final results
    losses_per_team = tuple([15-w for w in wins_per_team])
    score_per_team = tuple(scoring_array.sum(axis=1))
    label_per_team =  tuple(FF_2022_summary['Team_Name'])
    standings = pd.DataFrame(np.vstack((wins_per_team, losses_per_team, score_per_team)).T, index=label_per_team)
    standings = standings.rename(columns={0:'W', 1:'L', 2:'Pts'})    
    
    standings['Pts'] = standings['Pts'].astype(float)
    standings = standings.sort_values(by=['W', 'Pts'], ascending=[False, False])
    
    standings['Place'] = np.arange(1,13)
    standings['Playoffs'] = np.where(standings['Place'] < 5, 1, 0)
    standings['Top'] = np.where(standings['Place'] == 1, 1, 0)
    standings['Sacko'] = np.where(standings['Place'] > 10, 1, 0)
    
    places = np.array(standings['Place'])
    playoffs = np.array(standings['Playoffs'])
    tops = np.array(standings['Top'])
    sackos = np.array(standings['Sacko'])
    
    return standings

In [72]:
def simulate_many_seasons(FF_summary, sims = 2, fair=False):
    '''
    @sims is the number of simulations you would like to run.
    '''
    SCORES = simulate_one_season_scores(FF_summary)
    TOTAL = simulate_one_season_matchups(SCORES, fair=fair)
    
    for i in range(1,sims):
            
        SCORES = simulate_one_season_scores(FF_summary)
        SEASON_DF = simulate_one_season_matchups(SCORES, fair=fair)
        
        for col in TOTAL.columns.values:
            TOTAL[col] = TOTAL[col]/(i+1)*i + SEASON_DF[col]/(i+1) #Average is continusously updated across trials
    return TOTAL

def clean_total(total):
    total['W'] = round(total['W'], 2)
    total['L'] = 15-total['W']
    total['Pts'] = round(total['Pts'], 2)
    total['Place'] = round(total['Place'], 2)
    total['Playoffs'] = round(total['Playoffs'], 3)*100
    total['Top'] = round(total['Top'], 3)*100
    total['Sacko'] = round(total['Sacko'], 3)*100
    total = total.sort_values(by='Place')
    return total

# Run simulations

In [79]:
Sims = simulate_many_seasons(FF_2022_summary, sims = 100000)
Sims = clean_total(Sims)

In [80]:
print(sum(Sims['W']), sum(Sims['L']))
Sims

89.99 90.01

                              W     L      Pts  Place  Playoffs   Top  Sacko
GOBias Industries          9.01  5.99  1772.18   4.07      62.5  21.9    2.5
Brady = Washed Up IV       8.74  6.26  1747.70   4.50      56.3  17.0    3.5
Gee Whiz Darnell           8.66  6.34  1750.38   4.57      55.2  16.9    3.7
Pierogi Night              8.30  6.70  1707.32   5.27      45.8  10.8    5.9
Null Hypothesis            8.07  6.93  1720.56   5.46      42.5  10.5    6.5
Pay Dirt & Pylons II       8.13  6.87  1701.63   5.50      42.6   9.2    7.0
Movin' On Up               7.42  7.58  1653.13   6.69      27.8   4.7   13.3
PurpleVector Reunion Tour  7.12  7.88  1639.73   7.13      23.0   3.6   16.3
Sackwash Lyfe              6.99  8.01  1621.13   7.40      20.5   2.9   18.8
Jasjaap's Primo Team       6.25  8.75  1572.63   8.58      11.0   1.2   32.2
Schmop                     5.72  9.28  1533.61   9.33       6.6   0.6   43.6
Mr. Fans Noodle Haus       5.58  9.42  1527.48   9.50       6.1   0.6   46.8

In [81]:
Sims.to_excel('SimsRegular22.xlsx')

In [82]:
Sims2 = simulate_many_seasons(FF_2022_summary, sims = 100000, fair=True)
Sims2 = clean_total(Sims2)

In [83]:
print(sum(Sims2['W']), sum(Sims2['L']))
Sims2

89.99999999999999 90.00000000000001

                              W     L      Pts  Place  Playoffs   Top  Sacko
GOBias Industries          9.00  6.00  1772.46   4.00      63.5  22.2    2.4
Gee Whiz Darnell           8.71  6.29  1750.70   4.45      57.1  17.3    3.3
Brady = Washed Up IV       8.66  6.34  1746.70   4.55      55.5  16.2    3.6
Null Hypothesis            8.31  6.69  1720.92   5.12      47.5  11.9    5.3
Pierogi Night              8.11  6.89  1706.82   5.47      42.6   9.9    6.7
Pay Dirt & Pylons II       8.03  6.97  1701.31   5.60      41.0   9.0    7.4
Movin' On Up               7.37  7.63  1652.98   6.76      26.7   4.5   13.3
PurpleVector Reunion Tour  7.19  7.81  1640.27   7.06      23.5   3.8   15.7
Sackwash Lyfe              6.95  8.05  1621.80   7.48      19.5   2.9   19.3
Jasjaap's Primo Team       6.27  8.73  1572.48   8.61      10.8   1.2   32.1
Schmop                     5.74  9.26  1533.22   9.39       6.4   0.6   44.4
Mr. Fans Noodle Haus       5.66  9.34  1527.22   9.50       5.8   0.5   46.4

In [84]:
Sims2.to_excel('SimsRandom22.xlsx')